In [1]:
import numpy as np
import pandas as pd

# **Creating DataFrame**
for creating dataframe you can make it by list, array, dis etc...

In [4]:
data = {
    'Name' : ['John', 'Anna', 'Peter', 'Linda'],
    'Age' : [28,32,19,38],
    'City' : ['New York', 'Paris', 'Barlin', 'London'], 
    'Salary' : [65000, 80000, 62000, 75000]
}
df = pd.DataFrame(data)

In [5]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   80000
2  Peter   19    Barlin   62000
3  Linda   38    London   75000

In [32]:
data_list = [
    ['John',28,'New York', 65000],
    ['Anna', 32, 'Paris', 80000],
    ['Peter', 19, 'Barlin', 75000],
    ['Linda', 48, 'Londan', 62000]
]
df2 = pd.DataFrame(data_list)

In [33]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  32     Paris  80000
2  Peter  19    Barlin  75000
3  Linda  48    Londan  62000

If you want there is a columns name so you can do that by

In [34]:
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = columns)

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   80000
2  Peter   19    Barlin   75000
3  Linda   48    Londan   62000

# **Selection and Indexing of Colums**

If you want to target an specific column then

In [16]:
df2['City']

0    New York
1       Paris
2      Barlin
3      Londan
Name: City, dtype: object

I you want to target more then one column then

In [18]:
df2[['Name', 'City', 'Salary']]

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   80000
2  Peter    Barlin   75000
3  Linda    Londan   62000

# **Creating a new columns**

If you want to add new columns in DataFrame then you have to provide exactly no of value that present in Frame otherwise it gives error.

In [21]:
df2['Designation'] = ['Doctor', 'Engineering', 'Doctor', 'Engineering']

In [22]:
df2

    Name  Age      City  Salary  Designation
0   John   28  New York   65000       Doctor
1   Anna   32     Paris   80000  Engineering
2  Peter   19    Barlin   75000       Doctor
3  Linda   48    Londan   62000  Engineering

# **Removing Columns**
If you want to remove column in DataFrame the you have to use drop and provide axis by default it set 0 but here we want to remove designation column then we need to provide axis as 1.

In [23]:
df2.drop('Designation', axis = 1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   80000
2  Peter   19    Barlin   75000
3  Linda   48    Londan   62000

Here is a point that drop is not delete the column in main data it show that how the data look after remove.

For permanent delete you have to use *inplace = True*

In [25]:
df2.drop("Designation", axis = 1, inplace = True)

In [26]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   80000
2  Peter   19    Barlin   75000
3  Linda   48    Londan   62000

If you want to remove multiple Series then you can do it like that

In [36]:
df2.drop(['Age', 'Salary'], axis = 1)

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Barlin
3  Linda    Londan

In [37]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   32     Paris   80000
2  Peter   19    Barlin   75000
3  Linda   48    Londan   62000

In [39]:
df.drop(0,axis = 0)

    Name  Age    City  Salary
1   Anna   32   Paris   80000
2  Peter   19  Barlin   75000
3  Linda   48  Londan   62000

# **Selecting Row**
For selecting a row you have to use loc[] with DataFrame like that

In [40]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

And for selecting multiple row then

In [41]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   32     Paris   80000

# **Selecting Subsets of Row and Columns**

for selection subpart of table you have to provide first row detail in first[] and then column detail in 2nd [] like that.

In [42]:
df.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   80000

In [44]:
df2.loc[[2,3]][['Name', 'Age']]

    Name  Age
2  Peter   19
3  Linda   48

# **Condition Selection**

Example : I want to select those people whose age is more then 30

In [45]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   32   Paris   80000
3  Linda   48  Londan   62000

IF I inly want those people who is more then 30 and blongs to Paris

In [52]:
df2[(df2['Age'] > 30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   32  Paris   80000