In [1]:
import numpy as np 
import pandas as pd

# **Merging 2 DataFrames**

In [12]:
# DataFrame 1
employee = pd.DataFrame({
    "Employee_id" : [1,2,3,4,5],
    "Name" : ['John', "Anna", "Peter", "Linda", "Bob"],
    "Department" : ["HR", "IT", "Finance", "IT", "HR"]
})

# DataFrame 2
salaries = pd.DataFrame({
    "Employee_id" : [1,2,3,6,7],
    "Salary" : [50000, 72000, 55000, 80000, 45000],
    "Bonus" : [5000, 10000, 7000, 9000, 6000]
})

In [13]:
employee

   Employee_id   Name Department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [14]:
salaries

   Employee_id  Salary  Bonus
0            1   50000   5000
1            2   72000  10000
2            3   55000   7000
3            6   80000   9000
4            7   45000   6000

To merge these DataFrame we use *merge()*

In [16]:
pd.merge(employee, salaries, on= 'Employee_id', how= 'inner')

   Employee_id   Name Department  Salary  Bonus
0            1   John         HR   50000   5000
1            2   Anna         IT   72000  10000
2            3  Peter    Finance   55000   7000

In [18]:
pd.merge(employee, salaries, on= 'Employee_id', how= 'outer')

   Employee_id   Name Department   Salary    Bonus
0            1   John         HR  50000.0   5000.0
1            2   Anna         IT  72000.0  10000.0
2            3  Peter    Finance  55000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  80000.0   9000.0
6            7    NaN        NaN  45000.0   6000.0

In [19]:
pd.merge(employee, salaries, on='Employee_id', how='left')

   Employee_id   Name Department   Salary    Bonus
0            1   John         HR  50000.0   5000.0
1            2   Anna         IT  72000.0  10000.0
2            3  Peter    Finance  55000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [21]:
pd.merge(employee, salaries, on= "Employee_id", how= 'right')

   Employee_id   Name Department  Salary  Bonus
0            1   John         HR   50000   5000
1            2   Anna         IT   72000  10000
2            3  Peter    Finance   55000   7000
3            6    NaN        NaN   80000   9000
4            7    NaN        NaN   45000   6000

# **Concatination of 2 Dataframe**

In [22]:
df1 = pd.DataFrame({
    'A' : ['A0', 'A1', 'A2'],
    'B' : ['B0', 'B1', 'B2'],
    'C' : ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A' : ['A3', 'A4', 'A5'],
    'B' : ['B3', 'B4', 'B5'],
    'C' : ['C3', 'C4', 'C5']
})

In [23]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [24]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [25]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [26]:
pd.concat([df1, df2], axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# **Joining 2 DataFrame**

In [27]:
df1 = pd.DataFrame({
    'name' : ['Alice', 'Bob', "Charlie"]
}, index = [1,2,3])

df2 = pd.DataFrame({
    'score' : [85,90,75]
}, index = [2,3,4])

In [28]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [29]:
df2

   score
2     85
3     90
4     75

In [30]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [31]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0